package Entity;

public enum GameStages {
		DESCENT_STAGE_INIT,
		ASCENT_STAGE_INIT, 
		DESCENT_STAGE_RUNNING, 
		ASCENT_STAGE_RUNNING, 
		DESCENT_STAGE_PASSED,
		DESCENT_STAGE_PASSED_WAIT,
		ASCENT_STAGE_STANDBY,
		ASCENT_STAGE_PASSED,
		DESCENT_EXPLODE,
		ASCENT_EXPLODE,
		PAUSE
}
